import Images from "./src/Images/Images";

const cardData = [
    {
      carImage: `${Images.car}`,
      carName: "Toyota Camry 2018",
      badge: "Cheapest",
      routeMatch: "70% route match",
      seatsLeft: "1/3 seats left",
      driverImage: `${Images.person1}`,
      driverName: "Micheal",
      driverRating: "4.3 (23)",
      price: "47 TL",
      pickupLocation: "2 lane City hall street",
      pickupTime: "09:00 AM",
      travelDuration: "2h 30m",
      dropoffLocation: "Block 4, Caffe Couture",
      dropoffTime: "11:00 AM",
    },
    {
      carImage: `${Images.car}`,
      carName: "Honda Accord 2019",
      badge: "Verified",
      routeMatch: "80% route match",
      seatsLeft: "2/3 seats left",
      driverImage: `${Images.person2}`,
      driverName: "Sarah",
      driverRating: "4.8 (30)",
      price: "55 TL",
      pickupLocation: "Main Street",
      pickupTime: "10:30 AM",
      travelDuration: "2h 45m",
      dropoffLocation: "Central Park",
      dropoffTime: "01:15 PM",
    },
    {
      carImage: `${Images.car}`,
      carName: "Ford Mustang 2020",
      badge: "Closest",
      routeMatch: "90% route match",
      seatsLeft: "3/3 seats left",
      driverImage: `${Images.person3}`,
      driverName: "John",
      driverRating: "4.5 (25)",
      price: "60 TL",
      pickupLocation: "Downtown Square",
      pickupTime: "11:15 AM",
      travelDuration: "3h 00m",
      dropoffLocation: "Shopping Mall",
      dropoffTime: "02:30 PM",
    },
    {
      carImage: `${Images.car}`,
      carName: "Nissan Altima 2017",
      badge: "Cheapest",
      routeMatch: "75% route match",
      seatsLeft: "2/3 seats left",
      driverImage: `${Images.person2}`,
      driverName: "Alex",
      driverRating: "4.2 (20)",
      price: "50 TL",
      pickupLocation: "Business District",
      pickupTime: "10:00 AM",
      travelDuration: "2h 15m",
      dropoffLocation: "Tech Park",
      dropoffTime: "12:15 PM",
    },
    {
      carImage: `${Images.car}`,
      carName: "Tesla Model S 2021",
      badge: "Verified",
      routeMatch: "95% route match",
      seatsLeft: "1/3 seats left",
      driverImage: `${Images.person1}`,
      driverName: "Emily",
      driverRating: "4.9 (35)",
      price: "70 TL",
      pickupLocation: "Innovation Hub",
      pickupTime: "01:30 PM",
      travelDuration: "4h 30m",
      dropoffLocation: "Nature Park",
      dropoffTime: "06:00 PM",
    },
    // Add more card data objects as needed
  ];

  export default cardData